### ISSUE TITLE
Graphic glitch on embankments by roads

### ISSUE THREAD

**Issue by khagler** [klyte45/CS-FineRoadTool#4]
I found that if you use ground mode to create an embankment as close as possible to a road, there's a glitch where you can see through to the underside of the world--see attached screenshot. This can be worked around by making the bridge a little longer so there's a unit of space between the end of the embankment and the lower road.

![embankment_glitch](https://user-images.githubusercontent.com/1522554/72675297-0f2e4100-3a47-11ea-90dd-0ce304205d4b.jpg)

**Comment by klyte45** [comment]
It's not a mod bug, but a game limitation...
Closing.
